### ISSUE TITLE
more than 500 downloads for occurrence points?

### ISSUE THREAD

**Issue by wallaceEcoMod** [wallaceEcoMod/wallace#107]
A colleague recently complained that only up to 500 downloads were allowed. This was mainly due to a worry that huge downloads would lead to much higher processing times, and that users who wanted to use many more points could use the "User input" option. However, we should think about increasing this limit (or removing it completely?), as many users will be running Wallace on their own machines. 

From a suggestion from another colleague, we could also (or in addition?) add functionality to perform random subsamples of huge datasets, after removing duplicates. This would avoid lengthy computations later in the workflow. Something to ponder.

**Comment by BrunoVilela** [comment]
I though of two options: (1) like it is now, just increase the sample size allowed to the maximum; and (2) give the users an option for a random sample out of the complete dataset. In this we would download everything and then sample the size chosen by the user (make a warning that this option will be slower). The option 2 would avoid problems that happen because some of the downloads will be aggregated in whatever the first 500 data points are, by sampling the entire dataset we would give a more realistic distribution.

**Comment by ndimhypervol** [comment]
Maximum occurrence records for slider removed in v1.0.5, and replaced with input number with no maximum.
