### ISSUE TITLE
problem with wallace on Chinese laptops

### ISSUE THREAD

**Issue by meblair** [wallaceEcoMod/wallace#139]
Our workshop participants from China (who were using Lenovo Thinkpads) were unable to use Wallace. Our hypothesis is that its due to  an issue with the UTF8 interpreter for language. Attached is a photo of the error.  Not sure if this would also be an issue for japanese computers? 
![error](https://user-images.githubusercontent.com/40213942/42670454-2dc338a4-8685-11e8-9d69-9d5202d595d5.jpg)

**Comment by gepinillab** [comment]
Zijie and Song from China (participants in the workshop of Vietnam) encountered this error using wallace in R-studio during the SDM workshop. They found a TEMPORAL solution to solve it that they shared with us by email:
__________
When you using Chinese or other non-English system, after installed wallace, there was a warning jumped out: “Error in sub: input string 1 is invalid UTF-8” This is because in zone setting is Chinese. You can check through:
`Sys.getlocale(category = "LC_ALL")`

Then you can correct it there
`Sys.setlocale(category = "LC_ALL", locale = "English_United States.1252")`
____________

They could not fix the problem by coding.

**Comment by gepinillab** [comment]
To reproduce the error (before running Wallace):
` Sys.setlocale(category = "LC_ALL", locale = "Chinese")`

**Comment by gepinillab** [comment]
It looks like the problem is the encoding in Windows machines, and the no 'real' support of the UTF-8. The issue in the Chinese windows machines is for the use of non-ASCII characters (e.g., letters with accents") in the code. For this reason, I created a temporal branch that replaces all these characters for ASCII characters in all the package (e.g., á -> a). I will reach the Chinese colleagues to figure out if this temporal branch fixes the problem.

https://github.com/gepinillab/wallace/commit/503df51c451cc33891ccdb0e94d2e1df6024c44b
