### ISSUE TITLE
Error in .f: object 'Mean.AUC' not found

### ISSUE THREAD

**Issue by ValentinChCloud** [wallaceEcoMod/wallace#157]
Hello guys!

There is a problem a the step 6 "Model". I want to use Maxent,but the app is  crashing I got this error message in logs :
```
Error in .f: object 'Mean.AUC' not found
  105: .f
  104: map
  103: map_if
  102: vars_rename_eval
  101: tidyselect::vars_rename
  100: rename.data.frame
   98: function_list[[k]]
   96: freduce
   95: _fseq
   94: eval
   93: eval
   91: %>%
   90: <reactive> [modules/mod_c6_maxent.R#81]
   74: mod.maxent
   73: observeEventHandler [D:\Program Files\R\R-3.5.1\library\wallace\shiny/server.R#503]
    2: shiny::runApp
    1: run_wallace
```

 # Configuration
```
> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32 

> packageVersion("wallace")
[1] ‘1.0.5

```

**Comment by gepinillab** [comment]
Hi @ValentinChCloud,

I think that the error is because you have the new version of the `ENMeval` package (0.3.0; 
[https://groups.google.com/forum/#!topic/MAXENT/5iqJ0CPpIgI]) which one is using the `maxnet` package by default. We are working on a new version of `Wallace` (1.0.6) that will include maxent.jar and `maxnet` options. This version will fix the problem (~ 1 month).

If you have installed the new version of ENMeval package, a temporal solution is installing the v-0.2.2 from Github. You can use the following code:
```R
devtools::install_github("bobmuscarella/ENMeval@Version-0.2.2")
```
Please let me know if this temporal solution works for you.

Best,
Gonzalo

**Comment by ValentinChCloud** [comment]
Hi,

It seems to work, thank you !

But until the new version of wallace, can you specify which version of ENMval you want in the import description? If I understand well you call the last version in any case
https://github.com/wallaceEcoMod/wallace/blob/master/DESCRIPTION#L19

**Comment by gepinillab** [comment]
Good to know that works for you! Also, thanks for noticing the problem in the DESCRIPTION file. We will handle it soon.
