### ISSUE TITLE
Warning: Error in intI: index larger than maximal 185

### ISSUE THREAD

**Issue by Oliveira-D-R** [wallaceEcoMod/wallace#352]
After upgrading to the new version of wallace I am encountering a series of errors. The last one that appeared was:

*** Running ENMeval v2.0.0 with maxnet from maxnet package v0.1.2 ***

  |=========                                                                                  |  10%Registered S3 methods overwritten by 'adehabitatMA':
  method                       from
  print.SpatialPixelsDataFrame sp  
  print.SpatialPixels          sp  
  |=======================================================                                    |  60%Warning: from glmnet Fortran code (error code -186); Convergence for 186th lambda value not reached after maxit=100000 iterations; solutions for larger lambdas returned
Warning: Error in intI: index larger than maximal 185

**Comment by jamiemkass** [comment]
Were you not getting this error before with the previous Wallace version? This is a maxnet error that usually pops up when using hinge features on a big and complex dataset. Not sure why ENMeval 2 would throw this error if ENMeval 0.3.1 did not.

Can you also try models without hinges and report if this goes away? Just a note -- maxent.jar often does not error under these circumstances.

**Comment by Oliveira-D-R** [comment]
That worked! Thank you very much! It was the hinge. I also didn't understand why I didn't receive this error before the update. I will try to do it again using maxent.jar. Again, thank you very much.

**Comment by jamiemkass** [comment]
Great! Please let us know if you think ENMeval 2 is causing the error, and we can investigate. I am pretty sure this wouldn't be the case for this particular error though.

**Comment by gepinillab** [comment]
Hi @jamiemkass,

I decided to reopen this issue again because it was reported on the Google group. https://groups.google.com/g/wallaceEcoMod/c/4ofAiIL3Dbs

It looks like Ricardo Torres got a similar message after updating Wallace and ENMeval to their newest versions. Also, when he did not use Hinge, he got the issue with rangeModelMetadata (not sure if ecospat too).

I do not have a clue about the reason for the first issue. Any thoughts?

Best,
Gonzalo

**Comment by jamiemkass** [comment]
Has anyone confirmed that ENMeval 0.3.1 did not throw this error for maxnet on the same dataset? The only difference in implementation for maxnet is that 2.0.0 sets `addsamplestobackground` to TRUE for `maxnet()` to avoid this error (or a similar one).

What was the issue with rangeModelMetadata? This was not in Ricardo's post.

**Comment by gepinillab** [comment]
Users are reporting this error after updating to Wallace v1.1 (ENMeval 2.0). Ricardo told me via e-mail (no google group) that he did not have this problem using Wallace v1.0.6 (ENMeval 0.3). I am not sure about he was using the same dataset, but it is possible because he was using both versions (Wallace 1.06 and 1.1) on the same date. I think that we can ask him to test an ENMeval branch that has `addsamplestobackground = FALSE` to see if the problem persists.

About rangeModelMetadata, he got the following message after using maxnet without Hinge:

**Comment by gepinillab** [comment]
Okay. I already asked Ricardo to test a forked branch with `addsamplestobackground= FALSE`. Let´s wait to see if he has time to test it.

**Comment by gepinillab** [comment]
The version of maxnet that adds that parameter is not on CRAN. Ricardo will test if installing the maxnet version on Github fix the problem.

**Comment by gepinillab** [comment]
Installing maxnet from GitHub is not fixing the problem either. I will ask Bethany to see if we can obtain a reproducible dataset to obtain the same error. Still, I think that someone needs to approach Steven Phillips related to updating maxnet on CRAN.

**Comment by jamiemkass** [comment]
Okay, thanks. Must be some namespace issue with rangeModelMetadata. It should be installed with the installation of ENMeval. 

Concerning maxnet, we do need a reproducible example showing that 0.3.1 does not throw the error yet 2.0.0 does. Would appreciate if someone can investigate. Maybe Ricardo can send you some sample data?

**Comment by jamiemkass** [comment]
Steven Phillips said he'd make the CRAN update, and I just started dev on ENMeval 2.0.1 to fix some of these issues. Please see the new version on the master branch and try it out.

**Comment by gepinillab** [comment]
Awesome! Everything looks fine with ENMeval 2.0.1. I will ask Ricardo about the dataset.

**Comment by gepinillab** [comment]
Ricardo is using his own data, so it is not an option to get a reproducible error. However, Bethany will try to get one next week.
